name: excellxgene
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python=3.8
    - gcc
    - ipykernel
    - ipython
    - cxx-compiler
    - papermill
    - pip
    - pip:
        - excellxgene
        - scanpy
        - louvain
        - quilt3[catalog,pyarrow]
